In [1]:
from d2l import torch as d2l
import torch

In [3]:
X, W_xh = torch.normal(0, 1, (3, 1)), torch.normal(0, 1, (1, 4))
X, W_xh

(tensor([[-0.2318],
         [-0.4596],
         [ 0.2042]]),
 tensor([[-0.7421, -1.0241,  0.3572, -1.1814]]))

In [4]:
H, W_hh = torch.normal(0, 1, (3, 4)), torch.normal(0, 1, (4, 4))
H, W_hh

(tensor([[-1.5714, -0.8469, -0.3142,  0.4859],
         [-1.5696,  0.8965, -2.1252, -0.2532],
         [-1.7203, -0.3894, -1.3373,  0.7449]]),
 tensor([[ 1.7710, -1.5979,  0.4523, -1.8532],
         [ 0.0667, -0.6508,  0.2120, -0.0112],
         [-2.8134,  0.7826, -0.4296,  0.5409],
         [ 0.0800,  1.3568, -0.8312, -0.5379]]))

In [6]:
torch.matmul(X, W_xh)

tensor([[ 0.1720,  0.2374, -0.0828,  0.2738],
        [ 0.3411,  0.4706, -0.1641,  0.5429],
        [-0.1516, -0.2091,  0.0729, -0.2413]])

In [7]:
torch.matmul(H, W_hh)

tensor([[-1.9166,  3.4755, -1.1592,  2.4904],
        [ 3.2387, -0.0820,  0.6035,  1.8854],
        [ 0.7493,  2.9665, -0.9053,  2.0685]])

In [8]:
torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

tensor([[-1.7446,  3.7129, -1.2420,  2.7643],
        [ 3.5798,  0.3887,  0.4393,  2.4283],
        [ 0.5977,  2.7574, -0.8324,  1.8272]])

In [9]:
torch.cat((X, H), 1)

tensor([[-0.2318, -1.5714, -0.8469, -0.3142,  0.4859],
        [-0.4596, -1.5696,  0.8965, -2.1252, -0.2532],
        [ 0.2042, -1.7203, -0.3894, -1.3373,  0.7449]])

In [11]:
torch.cat((W_xh, W_hh), 0)

tensor([[-0.7421, -1.0241,  0.3572, -1.1814],
        [ 1.7710, -1.5979,  0.4523, -1.8532],
        [ 0.0667, -0.6508,  0.2120, -0.0112],
        [-2.8134,  0.7826, -0.4296,  0.5409],
        [ 0.0800,  1.3568, -0.8312, -0.5379]])

In [12]:
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[-1.7446,  3.7129, -1.2420,  2.7643],
        [ 3.5798,  0.3887,  0.4393,  2.4283],
        [ 0.5977,  2.7574, -0.8324,  1.8272]])