In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-2.7940e-09, grad_fn=<MeanBackward0>)

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 1.7817,  0.1043,  0.2139],
        [ 0.6244, -0.4389, -0.3656],
        [-0.5503,  1.0570,  1.4827],
        [ 1.2598, -0.3100, -0.5760],
        [-1.6699, -1.0044, -0.5889]], requires_grad=True)

In [7]:
dense.bias

Parameter containing:
tensor([-1.0234,  0.6330, -0.2131], requires_grad=True)

In [8]:
dense(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.7645, 0.5759]])

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[8.0873],
        [0.1015]])