In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [5]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [15]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))
    
net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

X, Y

(tensor([[ 0.3061, -0.2708,  0.2420,  0.0688,  0.7923, -0.4326, -0.2752, -0.6542,
          -0.3564,  1.5302, -1.2393,  0.3973,  1.3694,  1.6173,  1.7797, -0.1417,
           0.1592, -0.2414,  0.4525, -0.1264],
         [ 0.3580,  1.1403, -0.4721, -0.8526, -0.6550,  0.2997,  0.0207, -0.9061,
          -0.0734, -0.2340, -0.1712,  0.0261,  0.0526, -1.5926,  1.1381, -0.8659,
           1.8736,  0.8861, -0.9959, -0.2117]]),
 tensor([[-0.1563,  0.0689, -0.3023,  0.1985,  0.0115, -0.2455, -0.4067,  0.0457,
          -0.0904,  0.1049],
         [-0.2165,  0.1636, -0.3613,  0.0167,  0.1921, -0.0909, -0.0810,  0.2354,
          -0.0924,  0.3117]], grad_fn=<AddmmBackward>))

In [16]:
torch.save(net.state_dict(), 'mlp.params')

In [17]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [18]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])