In [1]:
from d2l import torch as d2l
import torch

In [2]:
def corr2d_multi_in(X, K):
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [6]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]], [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [7]:
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

In [8]:
K = torch.stack((K, K + 1, K + 2), 0)
K

tensor([[[[0., 1.],
          [2., 3.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[2., 3.],
          [4., 5.]]],


        [[[2., 3.],
          [4., 5.]],

         [[3., 4.],
          [5., 6.]]]])

In [9]:
K.shape

torch.Size([3, 2, 2, 2])

In [10]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [20]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h*w))
    print(X)
    K = K.reshape((c_o, c_i))
    print(K)
    Y = torch.matmul(K, X)
    print(Y)
    return Y.reshape((c_o, h, w))

In [21]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)
assert float(d2l.reduce_sum(torch.abs(Y1 - Y2))) < 1e-6

tensor([[ 1.4666,  0.0554,  1.2590,  1.0742,  0.9964, -0.2542,  1.1989,  1.1439,
         -0.3853],
        [-0.6975,  0.1738,  0.2713, -0.1652,  0.5248, -1.0440,  1.2841,  0.4873,
         -0.1158],
        [ 0.2332, -1.0720, -0.2325,  0.7370, -1.4051, -0.8461,  0.3700, -0.9568,
         -1.5618]])
tensor([[ 0.6873, -0.8220,  1.2722],
        [ 0.5453,  0.8939,  0.1686]])
tensor([[ 1.8779, -1.4686,  0.3466,  1.8117, -1.5341, -0.3930,  0.2393, -0.8317,
         -2.1566],
        [ 0.2155,  0.0048,  0.8898,  0.5623,  0.7755, -1.2145,  1.8640,  0.8980,
         -0.5770]])


In [22]:
X

tensor([[[ 1.4666,  0.0554,  1.2590],
         [ 1.0742,  0.9964, -0.2542],
         [ 1.1989,  1.1439, -0.3853]],

        [[-0.6975,  0.1738,  0.2713],
         [-0.1652,  0.5248, -1.0440],
         [ 1.2841,  0.4873, -0.1158]],

        [[ 0.2332, -1.0720, -0.2325],
         [ 0.7370, -1.4051, -0.8461],
         [ 0.3700, -0.9568, -1.5618]]])

In [23]:
K

tensor([[[[ 0.6873]],

         [[-0.8220]],

         [[ 1.2722]]],


        [[[ 0.5453]],

         [[ 0.8939]],

         [[ 0.1686]]]])

In [24]:
Y1

tensor([[[ 1.8779, -1.4686,  0.3466],
         [ 1.8117, -1.5341, -0.3930],
         [ 0.2393, -0.8317, -2.1566]],

        [[ 0.2155,  0.0048,  0.8898],
         [ 0.5623,  0.7755, -1.2145],
         [ 1.8640,  0.8980, -0.5770]]])

In [25]:
Y2

tensor([[[ 1.8779, -1.4686,  0.3466],
         [ 1.8117, -1.5341, -0.3930],
         [ 0.2393, -0.8317, -2.1566]],

        [[ 0.2155,  0.0048,  0.8898],
         [ 0.5623,  0.7755, -1.2145],
         [ 1.8640,  0.8980, -0.5770]]])

In [29]:
0.6873 * 1.4666 + (-0.8220) * (-0.6975) + (1.2722 * 0.2332)

1.8780162200000001